version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sql-ai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sql_ai_db}
      POSTGRES_USER: ${POSTGRES_USER:-sql_ai_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sql_ai_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sql_ai_user} -d ${POSTGRES_DB:-sql_ai_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: